In [1]:
from pathlib import Path

import pandas as pd

In [2]:
DATA_PATH = Path("./data")
OUTPUT_PATH = Path("./out")
GOLD_DATA_PATH = OUTPUT_PATH / "final_gold_data_embeddings.parquet"

In [3]:
gold = pd.read_parquet(GOLD_DATA_PATH)
gold.head()

,timestamp,open,high,low,close,volume,currency,unit,headlines,emb_nomic_1d,emb_nomic_7d,emb_nomic_dev_1d_7d
0,2000-08-30,273.9,273.9,273.9,273.9,0,usd,ounce,Recalls Fuel Disclosure Debate / Deutsche Tele...,"[0.016506249085068703, 0.05451096221804619, -0...","[0.016722846776247025, 0.05469881370663643, -0...","[-0.00021659769117832184, -0.00018785148859024..."
1,2000-08-31,274.8,278.3,274.8,278.3,0,usd,ounce,Credit Suisse's Wheat Faces Deal / Regulators ...,"[0.0030195650178939104, 0.0543488971889019, -0...","[0.01358045730739832, 0.04626588523387909, -0....","[-0.010560892289504409, 0.008083011955022812, ..."
2,2000-09-01,277.0,277.0,277.0,277.0,0,usd,ounce,Nordstrom's Chief Resigns / Judge Dismisses Ca...,"[0.00742419995367527, 0.015169485472142696, -0...","[0.018122855573892593, 0.03499217331409454, -0...","[-0.010698655620217323, -0.019822687841951847,..."
3,2000-09-05,275.8,275.8,275.8,275.8,2,usd,ounce,Market Pace Slows After 10-Year Run / Clickman...,"[-0.015742214396595955, 0.0482579730451107, -0...","[0.011489766649901867, 0.03651130944490433, -0...","[-0.027231981046497822, 0.011746663600206375, ..."
4,2000-09-06,274.2,274.2,274.2,274.2,0,usd,ounce,France Telecom Profit Increases / Locale-Based...,"[0.01789318583905697, 0.039853937923908234, -0...","[0.016275350004434586, 0.03585308417677879, -0...","[0.0016178358346223831, 0.00400085374712944, -..."

In [4]:
gold["headlines"].str.split("/").apply(len).value_counts().sort_index()

headlines
1      85
2     123
3     160
4     211
5     222
6     260
7     272
8     283
9     283
10    276
11    311
12    292
13    302
14    329
15    348
16    294
17    282
18    291
19    246
20    258
21    180
22    186
23    118
24    132
25    111
26     99
27     79
28     49
29     30
30     25
31     20
32      9
33      5
34      2
35      4
Name: count, dtype: int64

In [5]:
gold

,timestamp,open,high,low,close,volume,currency,unit,headlines,emb_nomic_1d,emb_nomic_7d,emb_nomic_dev_1d_7d
0,2000-08-30,273.9,273.9,273.9,273.9,0,usd,ounce,Recalls Fuel Disclosure Debate / Deutsche Tele...,"[0.016506249085068703, 0.05451096221804619, -0...","[0.016722846776247025, 0.05469881370663643, -0...","[-0.00021659769117832184, -0.00018785148859024..."
1,2000-08-31,274.8,278.3,274.8,278.3,0,usd,ounce,Credit Suisse's Wheat Faces Deal / Regulators ...,"[0.0030195650178939104, 0.0543488971889019, -0...","[0.01358045730739832, 0.04626588523387909, -0....","[-0.010560892289504409, 0.008083011955022812, ..."
2,2000-09-01,277.0,277.0,277.0,277.0,0,usd,ounce,Nordstrom's Chief Resigns / Judge Dismisses Ca...,"[0.00742419995367527, 0.015169485472142696, -0...","[0.018122855573892593, 0.03499217331409454, -0...","[-0.010698655620217323, -0.019822687841951847,..."
3,2000-09-05,275.8,275.8,275.8,275.8,2,usd,ounce,Market Pace Slows After 10-Year Run / Clickman...,"[-0.015742214396595955, 0.0482579730451107, -0...","[0.011489766649901867, 0.03651130944490433, -0...","[-0.027231981046497822, 0.011746663600206375, ..."
4,2000-09-06,274.2,274.2,274.2,274.2,0,usd,ounce,France Telecom Profit Increases / Locale-Based...,"[0.01789318583905697, 0.039853937923908234, -0...","[0.016275350004434586, 0.03585308417677879, -0...","[0.0016178358346223831, 0.00400085374712944, -..."
...,...,...,...,...,...,...,...,...,...,...,...,...
6172,2025-04-08,2994.0,3014.5,2968.4,2968.4,3213,usd,ounce,South Korea Announces Emergency Support for Au...,"[-0.029566632583737373, 0.040715575218200684, ...","[-0.01662260852754116, 0.034705936908721924, 0...","[-0.012944024056196213, 0.00600963830947876, -..."
6173,2025-04-09,2965.8,3090.4,2965.8,3056.5,2175,usd,ounce,Inside the Chinese City That Said Cash Rewards...,"[-0.03097187913954258, 0.06482727080583572, -0...","[-0.02385895885527134, 0.0347687304019928, -0....","[-0.00711292028427124, 0.030058540403842926, -..."
6174,2025-04-10,3073.9,3167.0,3072.1,3155.2,3456,usd,ounce,Six Dead in Helicopter Crash in Hudson River N...,"[-0.001429373282007873, 0.021974442526698112, ...","[-0.029724551364779472, 0.05269043147563934, -...","[0.0282951780827716, -0.03071598894894123, -0...."
6175,2025-04-11,3182.1,3235.0,3182.1,3222.2,862,usd,ounce,Spanish Siemens Couple Killed Alongside Childr...,"[0.008680936880409718, 0.006411557551473379, -...","[-0.022493112832307816, 0.05082451552152634, -...","[0.031174049712717533, -0.04441295797005296, -..."
6176,2025-04-14,3215.5,3228.8,3194.5,3204.8,263,usd,ounce,Star Posts Large Loss in Delayed First-Half Re...,"[-0.017825359478592873, 0.05848882719874382, -...","[-0.004211800172924995, 0.03510737791657448, -...","[-0.013613559305667877, 0.023381449282169342, ..."

In [6]:
gold.info()

<class 'pandas.DataFrame'>
RangeIndex: 6177 entries, 0 to 6176
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            6177 non-null   datetime64[us]
 1   open                 6177 non-null   float64
 2   high                 6177 non-null   float64
 3   low                  6177 non-null   float64
 4   close                6177 non-null   float64
 5   volume               6177 non-null   int64
 6   currency             6177 non-null   str
 7   unit                 6177 non-null   str
 8   headlines            6177 non-null   str
 9   emb_nomic_1d         6177 non-null   object
 10  emb_nomic_7d         6177 non-null   object
 11  emb_nomic_dev_1d_7d  6177 non-null   object
dtypes: datetime64[us](1), float64(4), int64(1), object(3), str(3)
memory usage: 4.5+ MB